---
rhpds_build_secured_dev_workflows_developer_hub_quay_namespace: quay-enterprise
rhpds_build_secured_dev_workflows_developer_hub_namespace: backstage
rhpds_build_secured_dev_workflows_developer_hub_argocd_namespace: tssc-gitops
rhpds_build_secured_dev_workflows_developer_hub_keycloak_namespace: tssc-keycloak
rhpds_build_secured_dev_workflows_developer_hub_devspaces_namespace: openshift-devspaces

rhpds_build_secured_dev_workflows_developer_hub_keycloak_client_id: developer-hub
rhpds_build_secured_dev_workflows_developer_hub_keycloak_client_secret: ""
rhpds_build_secured_dev_workflows_developer_hub_authentication_realm: sso

rhpds_build_secured_dev_workflows_developer_hub_quay_registry: quay.io
rhpds_build_secured_dev_workflows_developer_hub_quay_image: rhdh/rhdh-hub-rhel9
rhpds_build_secured_dev_workflows_developer_hub_quay_image_tag: "1.7"

rhpds_build_secured_dev_workflows_developer_hub_catalog_locations:
- repository: build_secured_dev_workflows_idp_configuration
  revision: main
  group: rhdh
  file:
  - all-locations.yaml

rhpds_build_secured_dev_workflows_developer_hub_templating_files:
- repository: build_secured_dev_workflows_idp_configuration
  revision: main
  group: rhdh
  file:
  - component-rhpds.yaml
- repository: build_secured_dev_workflows_idp_gitops
  revision: main
  group: gitops
  file:
  - charts/backstage/backstage-values.yaml


rhpds_build_secured_dev_workflows_developer_hub_helm_chart_repo: https://charts.openshift.io
rhpds_build_secured_dev_workflows_developer_hub_helm_chart: redhat-developer-hub
rhpds_build_secured_dev_workflows_developer_hub_helm_chart_version: 1.7.1

rhpds_build_secured_dev_workflows_developer_hub_gitlab_user_base_name: user
rhpds_build_secured_dev_workflows_developer_hub_gitlab_password: ""
rhpds_build_secured_dev_workflows_developer_hub_user_base_name: user
rhpds_build_secured_dev_workflows_developer_hub_num_users: 1
rhpds_build_secured_dev_workflows_developer_hub_user_password: ""

rhpds_build_secured_dev_workflows_developer_hub_rhacs_namespace: stackrox
rhpds_build_secured_dev_workflows_developer_hub_rhacs_admin_user: admin
rhpds_build_secured_dev_workflows_developer_hub_rhacs_admin_password: "{{ common_password }}"

rhpds_build_secured_dev_workflows_developer_hub_argocd_user: admin
rhpds_build_secured_dev_workflows_developer_hub_argocd_password: "{{ common_password }}"

rhpds_build_secured_dev_workflows_developer_hub_gitlab_namespace: gitlab
rhpds_build_secured_dev_workflows_developer_hub_gitlab_root_user: root
rhpds_build_secured_dev_workflows_developer_hub_gitlab_root_password: "{{ common_password }}"

rhpds_build_secured_dev_workflows_developer_hub_quay_admin_user: quayadmin
rhpds_build_secured_dev_workflows_developer_hub_quay_admin_password: "{{ common_password }}"

rhpds_build_secured_dev_workflows_developer_hub_nginx_namespace: nginx
